import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCES = ['src/styles/tokens.css', 'src/styles/app-tokens.css'];
const OUT = resolve(root, 'src/design-system/theme/tokens.generated.ts');
const COLOR = /^(#[0-9a-f]{3,8}|rgba?\([^()]*\))$/i;

// Returns [{ selector, body }] for every rule at any nesting depth, flattening @layer/@media wrappers.
function collectRules(css) {
  const rules = [];
  const walk = (text) => {
    let i = 0;
    while (i < text.length) {
      const open = text.indexOf('{', i);
      if (open === -1) break;
      let depth = 1;
      let j = open + 1;
      while (j < text.length && depth > 0) {
        if (text[j] === '{') depth++;
        else if (text[j] === '}') depth--;
        j++;
      }
      const selector = text.slice(i, open).trim();
      const body = text.slice(open + 1, j - 1);
      if (selector.startsWith('@')) walk(body);
      else rules.push({ selector, body });
      i = j;
    }
  };
  walk(css.replace(/\/\*[\s\S]*?\*\//g, ''));
  return rules;
}

function declarations(body) {
  const out = [];
  for (const m of body.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) out.push([m[1], m[2].trim()]);
  return out;
}

const light = new Map();
const night = new Map();
for (const file of SOURCES) {
  for (const { selector, body } of collectRules(readFileSync(resolve(root, file), 'utf8'))) {
    const target = selector === ':root' ? light : selector === '[data-theme="night"]' ? night : null;
    if (!target) continue;
    for (const [name, value] of declarations(body)) target.set(name, value);
  }
}

function resolveAll(table) {
  const resolveOne = (name, seen = new Set()) => {
    const raw = table.get(name);
    if (raw === undefined || seen.has(name)) return undefined;
    seen.add(name);
    const single = raw.match(/^var\((--[\w-]+)\)$/);
    return single ? resolveOne(single[1], seen) : raw;
  };
  const out = {};
  for (const name of table.keys()) {
    const value = resolveOne(name);
    if (value && COLOR.test(value)) out[name] = value;
  }
  return out;
}

const nightMerged = new Map([...light, ...night]);
const lightResolved = resolveAll(light);
const nightResolved = resolveAll(nightMerged);

// Browser chrome colour cannot be read from a stylesheet, so it mirrors the surface token.
lightResolved['--theme-color-terminal'] = lightResolved['--surface'];
nightResolved['--theme-color-night'] = nightResolved['--surface'];
lightResolved['--theme-color-night'] = nightResolved['--surface'];
nightResolved['--theme-color-terminal'] = lightResolved['--surface'];

const emit = (name, table) =>
  `export const ${name}: Record<string, string> = {\n` +
  Object.entries(table)
    .map(([k, v]) => `  '${k}': '${v}',`)
    .join('\n') +
  '\n};\n';

const output =
  '/* Generated by scripts/generate-tokens.mjs from src/styles/tokens.css and app-tokens.css; do not edit. */\n' +
  emit('TOKEN_FALLBACKS', lightResolved) +
  '\n' +
  emit('TOKEN_FALLBACKS_NIGHT', nightResolved);

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    // A missing file counts as stale.
  }
  if (current.replace(/\r\n/g, '\n') !== output) {
    console.error('tokens.generated.ts is stale: run `npm run tokens`.');
    process.exit(1);
  }
} else {
  writeFileSync(OUT, output);
  console.log(`Wrote ${OUT}`);
}
